# Generated by Django 4.0.1 on 2022-01-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilecourses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='rated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
